<?php

namespace MainBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageRepository extends EntityRepository
{
    /**
     * @param $id
     * @return \Doctrine\ORM\Query
     */
    public function getImagesByAlbumIdDQL($id)
    {
        $dql = $this->createQueryBuilder('p');
        $dql->where('p.album = :album_id');
        $dql->setParameters(array('album_id' => (int) $id));
        return $dql;
    }
}
